### ISSUE TITLE
How to run the sample app?

### ISSUE THREAD

**Issue by oren** [prateekbh/preact-material-components#10]
Can you please provide the steps to try out this website/app?

**Comment by prateekbh** [comment]
This app is right now super fragile.
I'll keep this open to add the final comment later, but for now.
Run webpack from sample folder and serve the root folder with any server node http-server or simple python server. And Hopefully it'll work at /sample url.
Sorry for how messy this is right now.

**Comment by oren** [comment]
I am getting an error. would you elaborate a bit about the steps I should take?

I do the following:
```
npm install
cd sample
webpack
```

And I see the following error:
```
ERROR in multi vendor
Module not found: Error: Cannot resolve module 'preact' in /home/oren/p/preact/preact-material-components/sample
 @ multi vendor

ERROR in ./app.jsx
Module parse failed: /home/oren/p/preact/preact-material-components/sample/app.jsx Unexpected token (5:1)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (5:1)
    at Parser.pp$4.raise (/usr/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/usr/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/usr/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/usr/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/usr/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/usr/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/usr/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/usr/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExprList (/usr/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:2165:22)
    at Parser.pp$3.parseSubscripts (/usr/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1741:35)
    at Parser.pp$3.parseExprSubscripts (/usr/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1718:17)
    at Parser.pp$3.parseMaybeUnary (/usr/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/usr/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/usr/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/usr/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/usr/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/usr/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:727:47)
    at Parser.pp$1.parseTopLevel (/usr/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/usr/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/usr/lib/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/usr/lib/node_modules/webpack/lib/Parser.js:902:15)
    at NormalModule.<anonymous> (/usr/lib/node_modules/webpack/lib/NormalModule.js:104:16)
    at NormalModule.onModuleBuild (/usr/lib/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/usr/lib/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /usr/lib/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /usr/lib/node_modules/webpack/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:438:3)
```

**Comment by prateekbh** [comment]
Okay here you go,
1.) take a pull
2.) npm install
3.) cd sample
4.) webpack
5.) cd ..
6.) http-server .

**Comment by prateekbh** [comment]
@oren lemme know if this works for you

**Comment by oren** [comment]
Thanks Prateek!
I get the same error as above on step 4.

**Comment by prateekbh** [comment]
Can u do an independent npm i preact

**Comment by oren** [comment]
I tried it and got the same error.

more info about my system:
* node 7.7.1
* npm 4.1.2
* Ubuntu 16.04.2 LTS

**Comment by Download** [comment]
I am seeing something similar:

```sh
c:\ws\preact-material-components-1\sample>webpack
clean-webpack-plugin: C:\ws\preact-material-components-1\sample\public has been removed.
Hash: 301be937476ffe4c724d
Version: webpack 1.12.10
Time: 136ms
    Asset     Size  Chunks             Chunk Names
vendor.js  25.5 kB       0  [emitted]  vendor
   [0] multi vendor 28 bytes {0} [built]
   [0] ./app.jsx 0 bytes [built] [failed]
    + 1 hidden modules

ERROR in ./app.jsx
Module parse failed: c:\ws\preact-material-components-1\sample\app.jsx Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import {h, render} from 'preact';
| import Home from './home.jsx';
|
```

It seems like a Babel issue. Main project works as expected, just the sample has this issue.

**Comment by prateekbh** [comment]
I am actually now quickly shifting to gh-pages, can you guys try that?
That'll be simillar kinda playground

**Comment by oren** [comment]
I am not sure if that's what you meant but here are my steps:
```
git checkout gh-pages
npm i
webpack
```

And the output is a lot of warnings and also this error:
```
ERROR in ./~/preact-material-components/Toolbar/index.js
Module parse failed: /home/oren/p/preact/preact-material-components/node_modules/babel-loader/lib/index.js??ref--0!/home/oren/p/preact/preact-material-components/node_modules/preact-material-components/Toolbar/index.js Unexpected token (87:5)
You may need an appropriate loader to handle this file type.
|                               "section",
|                               null,
|                               {...props}
|                       );
|               }
 @ ./Components/Home/Home.jsx 11:0-57
 @ ./app.js
```

**Comment by Download** [comment]
Ok, so try this:

```sh
webpack --version
```

For me, it turns out my *global* Webpack install was still Webpack 1....  :(

**Comment by Download** [comment]
Ok, so with Webpack 2, I get a bit further:

```sh
c:\ws\preact-material-components-1\sample>webpack --version
2.3.3

c:\ws\preact-material-components-1\sample>webpack
clean-webpack-plugin: C:\ws\preact-material-components-1\sample\public has been removed.
(node:9112) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Hash: d4450a89ecba232b4350
Version: webpack 2.3.3
Time: 1271ms
    Asset     Size  Chunks             Chunk Names
   app.js  10.6 kB       0  [emitted]  app
vendor.js  31.8 kB       1  [emitted]  vendor
   [0] ../~/preact/dist/preact.js 25.3 kB {1} [built]
   [1] ./home.jsx 5.18 kB {0} [built]
   [2] ./app.jsx 122 bytes {0} [built]
   [3] multi preact 28 bytes {1} [built]

ERROR in ./home.jsx
Module not found: Error: Can't resolve '../Components/' in 'c:\ws\preact-material-components-1\sample'
 @ ./home.jsx 10:0-144
 @ ./app.jsx
```

It seems this is a real error... There is no folder Components.

Changing the import path to `../` seems to fix it:

```sh
c:\ws\preact-material-components-1>webpack
(node:2136) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Hash: f1b53a8b9d39e21eb64f
Version: webpack 2.3.2
Time: 4698ms
   Asset    Size  Chunks                    Chunk Names
index.js  332 kB       0  [emitted]  [big]  main
   [4] ./Button/index.js 3.38 kB {0} [built]
   [5] ./List/index.js 4.79 kB {0} [built]
  [10] ./Card/index.js 6.21 kB {0} [built]
  [11] ./Checkbox/index.js 3.22 kB {0} [built]
  [12] ./Dialog/index.js 5.66 kB {0} [built]
  [13] ./Drawer/index.js 7 kB {0} [built]
  [14] ./Elevation/index.js 2.68 kB {0} [built]
  [16] ./FormField/index.js 2.19 kB {0} [built]
  [17] ./Icon/index.js 2.38 kB {0} [built]
  [18] ./Radio/index.js 2.91 kB {0} [built]
  [19] ./Select/index.js 2.96 kB {0} [built]
  [20] ./Snackbar/index.js 2.73 kB {0} [built]
  [21] ./Switch/index.js 2.3 kB {0} [built]
  [22] ./Textfield/index.js 3.11 kB {0} [built]
  [23] ./index.js 604 bytes {0} [built]
    + 36 hidden modules
```

PR coming up...

**Comment by Download** [comment]
@prateekbh 

I am not able to start the HTTP server:

```sh
c:\ws\preact-material-components-1>http-server .
'http-server' is not recognized as an internal or external command,
operable program or batch file.
```

As you can see I am on Windows... not sure if that;s relevant.

Should I install something globally perhaps?

**Comment by prateekbh** [comment]
@Download http-server is  a node server
run `npm -g http-server`

Also i am starting to build gh-pages. sample folder was just a temporary work around, which i am looking forward to remove in some days

**Comment by prateekbh** [comment]
@oren @Download can you guys try running the gh-pages branch instead.
its a WIP, but should guarantee a proper build

**Comment by Download** [comment]
I tried the `gh_pages` branch:

```sh
C:\ws\preact-material-components-1>webpack
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
clean-webpack-plugin: C:\ws\preact-material-components-1\public has been removed.
(node:14780) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Hash: 29fe396fe7dbfb4cc211
Version: webpack 2.3.2
Time: 9747ms
    Asset     Size  Chunks             Chunk Names
   app.js   113 kB       0  [emitted]  app
vendor.js  31.8 kB       1  [emitted]  vendor
  app.css   158 kB       0  [emitted]  app
   [0] ./~/preact/dist/preact.js 25.3 kB {1} [built]
   [5] ./~/preact-material-components/List/index.js 4.79 kB {0} [built]
   [6] ./Components/Home/Home.jsx 5.75 kB {0} [built]
   [7] ./app.css 41 bytes {0} [built]
   [8] ./~/preact-material-components/Theme/Theme.css 41 bytes {0} [built]
   [9] ./~/preact-material-components/Typography/Typography.css 41 bytes {0} [built]
  [10] ./app.js 303 bytes {0} [built]
  [25] ./~/preact-material-components/Icon/Icon.css 41 bytes {0} [built]
  [26] ./~/preact-material-components/List/List.css 41 bytes {0} [built]
  [27] ./~/preact-material-components/Toolbar/Toolbar.css 41 bytes {0} [built]
  [28] multi preact 28 bytes {1} [built]
  [37] ./~/css-loader!./~/postcss-loader!./app.css 249 bytes [built]
  [41] ./~/css-loader!./~/postcss-loader!./~/preact-material-components/Theme/Theme.css 10.7 kB [built]
  [43] ./~/css-loader!./~/postcss-loader!./~/preact-material-components/Typography/Typography.css 6.92 kB [built]
  [44] ./~/style-loader/addStyles.js 8.51 kB [built]
    + 30 hidden modules

WARNING in ./~/css-loader!./~/postcss-loader!./~/preact-material-components/Icon/Icon.css
(Emitted value instead of an instance of Error) postcss-custom-properties: C:\ws\preact-material-components-1\node_modules\preact-material-components\Icon\Icon.css:392:3: Custom property ignored: not scoped to the top-level :root element (.mdc-icon-toggle { ... --mdc-ripple-left: ... })
 @ ./~/preact-material-components/Icon/Icon.css 4:14-93
 @ ./Components/Home/Home.jsx
 @ ./app.js

(snipped many similar warnings)

ERROR in ./~/preact-material-components/Toolbar/index.js
Module parse failed: C:\ws\preact-material-components-1\node_modules\babel-loader\lib\index.js??ref--0!C:\ws\preact-material-components-1\node_modules\preact-material-components\Toolbar\index.js Unexpected token (87:5)
You may need an appropriate loader to handle this file type.
|                               "section",
|                               null,
|                               {...props}
|                       );
|               }
 @ ./Components/Home/Home.jsx 11:0-57
 @ ./app.js
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 2.19 kB {0} [built]
       [1] ./~/base64-js/index.js 3.5 kB {0} [built]
       [2] ./~/buffer/index.js 48.8 kB {0} [built]
       [3] ./~/ieee754/index.js 2.08 kB {0} [built]
       [4] ./~/isarray/index.js 131 bytes {0} [built]
       [5] (webpack)/buildin/global.js 808 bytes {0} [built]
       [6] ./~/css-loader!./~/postcss-loader!./app.css 249 bytes {0} [built]
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 2.19 kB {0} [built]
       [1] ./~/base64-js/index.js 3.5 kB {0} [built]
       [2] ./~/buffer/index.js 48.8 kB {0} [built]
       [3] ./~/ieee754/index.js 2.08 kB {0} [built]
       [4] ./~/isarray/index.js 131 bytes {0} [built]
       [5] (webpack)/buildin/global.js 808 bytes {0} [built]
       [6] ./~/css-loader!./~/postcss-loader!./Components/Home/Home.css 328 bytes {0} [built]
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 2.19 kB {0} [built]
       [1] ./~/base64-js/index.js 3.5 kB {0} [built]
       [2] ./~/buffer/index.js 48.8 kB {0} [built]
       [3] ./~/ieee754/index.js 2.08 kB {0} [built]
       [4] ./~/isarray/index.js 131 bytes {0} [built]
       [5] (webpack)/buildin/global.js 808 bytes {0} [built]
       [6] ./~/css-loader!./~/postcss-loader!./~/preact-material-components/Typography/Typography.css 6.92 kB {0} [built]
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 2.19 kB {0} [built]
       [1] ./~/base64-js/index.js 3.5 kB {0} [built]
       [2] ./~/buffer/index.js 48.8 kB {0} [built]
       [3] ./~/ieee754/index.js 2.08 kB {0} [built]
       [4] ./~/isarray/index.js 131 bytes {0} [built]
       [5] (webpack)/buildin/global.js 808 bytes {0} [built]
       [6] ./~/css-loader!./~/postcss-loader!./~/preact-material-components/Theme/Theme.css 10.7 kB {0} [built]
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 2.19 kB {0} [built]
       [1] ./~/base64-js/index.js 3.5 kB {0} [built]
       [2] ./~/buffer/index.js 48.8 kB {0} [built]
       [3] ./~/ieee754/index.js 2.08 kB {0} [built]
       [4] ./~/isarray/index.js 131 bytes {0} [built]
       [5] (webpack)/buildin/global.js 808 bytes {0} [built]
       [6] ./~/css-loader!./~/postcss-loader!./~/preact-material-components/Drawer/Drawer.css 56.2 kB {0} [built]
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 2.19 kB {0} [built]
       [1] ./~/base64-js/index.js 3.5 kB {0} [built]
       [2] ./~/buffer/index.js 48.8 kB {0} [built]
       [3] ./~/ieee754/index.js 2.08 kB {0} [built]
       [4] ./~/isarray/index.js 131 bytes {0} [built]
       [5] (webpack)/buildin/global.js 808 bytes {0} [built]
       [6] ./~/css-loader!./~/postcss-loader!./~/preact-material-components/Icon/Icon.css 37.4 kB {0} [built] [11 warnings]

    WARNING in ./~/css-loader!./~/postcss-loader!./~/preact-material-components/Icon/Icon.css
    (Emitted value instead of an instance of Error) postcss-custom-properties: C:\ws\preact-material-components-1\node_modules\preact-material-components\Icon\Icon.css:392:3: Custom property ignored: not scoped to the top-level :root element (.mdc-icon-toggle { ... --mdc-ripple-left: ... })

(Snipped many similar warnings)

Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 2.19 kB {0} [built]
       [1] ./~/base64-js/index.js 3.5 kB {0} [built]
       [2] ./~/buffer/index.js 48.8 kB {0} [built]
       [3] ./~/ieee754/index.js 2.08 kB {0} [built]
       [4] ./~/isarray/index.js 131 bytes {0} [built]
       [5] (webpack)/buildin/global.js 808 bytes {0} [built]
       [6] ./~/css-loader!./~/postcss-loader!./~/preact-material-components/Toolbar/Toolbar.css 16.5 kB {0} [built]
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 2.19 kB {0} [built]
       [1] ./~/base64-js/index.js 3.5 kB {0} [built]
       [2] ./~/buffer/index.js 48.8 kB {0} [built]
       [3] ./~/ieee754/index.js 2.08 kB {0} [built]
       [4] ./~/isarray/index.js 131 bytes {0} [built]
       [5] (webpack)/buildin/global.js 808 bytes {0} [built]
       [6] ./~/css-loader!./~/postcss-loader!./~/preact-material-components/List/List.css 36.4 kB {0} [built] [11 warnings]

(Snipped more warnings)
```

**Comment by prateekbh** [comment]
yeah, can you take a pull?
it was because of some extra post-css pluging which i have removes,

take a pull
do npm install
and then webpack

**Comment by prateekbh** [comment]
i just deleted my folder from my machine and re cloned it... worked fine, lemme know if this still breaks

**Comment by Download** [comment]
> take a pull

Is this the `gh_pages` branch you are talking about? Because I did a pull and got 
> Already up-to-date.

```sh
git.exe pull --progress -v --no-rebase "origin"

From github.com:Download/preact-material-components-1
= [up to date]      gh-pages   -> origin/gh-pages
= [up to date]      bugFixes   -> origin/bugFixes
= [up to date]      bundling   -> origin/bundling
= [up to date]      issue-10   -> origin/issue-10
= [up to date]      issue-28   -> origin/issue-28
= [up to date]      master     -> origin/master
= [up to date]      toolbarBugFixes -> origin/toolbarBugFixes
Already up-to-date.

Success (3594 ms @ 4-4-2017 13:18:07)

I ran `npm install` again just to be sure. It reported no changes. Then ran `webpack`, but still getting the same result.

**Comment by Download** [comment]
Oops sorry! Should pull from `upstream`, not `origin`! Let me retry!

**Comment by Download** [comment]
After pulling from `upstream`, running `webpack` command in the repo root gives no errors.

However if I cd into `samples` folder and run `webpack` there, it still gives errors:

```sh
c:\ws\preact-material-components-1\sample>webpack
clean-webpack-plugin: C:\ws\preact-material-components-1\sample\public has been removed.
(node:10248) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Hash: ef97489a5a4e0adfd9f3
Version: webpack 2.3.3
Time: 5384ms
    Asset     Size  Chunks             Chunk Names
vendor.js  28.4 kB       0  [emitted]  vendor
   [0] ../~/preact/dist/preact.js 25.3 kB {0} [built]
   [1] multi preact 28 bytes {0} [built]

ERROR in Entry module not found: Error: Can't resolve './app.jsx' in 'c:\ws\preact-material-components-1\sample'
```

I installed `http-server` but not sure how to proceed next.

**Comment by prateekbh** [comment]
@Download  if you are in `gh-pages` branch, please ignore the `sample` folder completely.
`Sample` folder is being deprecated.
run webpack in root folder 

and run `http-server .`

then go to `localhost:8080`

**Comment by prateekbh** [comment]
I see the pain there @Download @oren, hence adding the script in `gh-pages`

just take a pull and `npm start` to start the server.

**Comment by oren** [comment]
works! i am new to React/Preact. would you mind sharing the steps to use it from my preact app?

**Comment by prateekbh** [comment]
@oren that'll be documented at 
Prateekbh.github.io/preact-material-components soon

**Comment by prateekbh** [comment]
@Download if you can confirm the same i'll close the issue

**Comment by Download** [comment]
Yes it works great.

Also it looks like you are pretty far along already. Great work man!
