### ISSUE TITLE
#268 introduced a bug in CssMigrationWebpackPlugin

### ISSUE THREAD

**Issue by filoozom** [prateekbh/preact-material-components#273]
```
> preact-material-components@1.1.6 build /home/travis/build/prateekbh/preact-material-components
> node ./compileComponents.js && webpack
Error: no such file or directory: /home/travis/build/prateekbh/preact-material-components/node_modules/@material/button/dist/mdc.button.css
    at Function.sync (/home/travis/build/prateekbh/preact-material-components/node_modules/cp/index.js:75:11)
    at CssMigrationWebpackPlugin.copyIndividualCss (/home/travis/build/prateekbh/preact-material-components/CssMigrationWebpackPlugin.js:37:6)
    at Compiler.compiler.plugin (/home/travis/build/prateekbh/preact-material-components/CssMigrationWebpackPlugin.js:52:12)
    at Compiler.applyPluginsAsyncSeries1 (/home/travis/build/prateekbh/preact-material-components/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/home/travis/build/prateekbh/preact-material-components/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/home/travis/build/prateekbh/preact-material-components/node_modules/webpack/lib/Compiler.js:354:15)
    at /home/travis/build/prateekbh/preact-material-components/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/home/travis/build/prateekbh/preact-material-components/node_modules/async/dist/async.js:998:13)
    at /home/travis/build/prateekbh/preact-material-components/node_modules/async/dist/async.js:906:16
    at /home/travis/build/prateekbh/preact-material-components/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:136:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! preact-material-components@1.1.6 build: `node ./compileComponents.js && webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the preact-material-components@1.1.6 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2017-09-21T07_08_54_979Z-debug.log
npm ERR! Test failed.  See above for more details.
The command "./scripts/travis.sh $TEST_DIR" exited with 1.
```

Faulty line: https://github.com/prateekbh/preact-material-components/blob/056d8329acfb81351de14d26461f66714868a548/CssMigrationWebpackPlugin.js#L37

**Comment by filoozom** [comment]
Apparently it's because ```@material/button/dist/mdc.button.css``` doesn't exist, but this seems to work on NodeJS 7 and only fails on NodeJS 8.

**Comment by prateekbh** [comment]
woahhhh something changed... there's no button in `@ material`

**Comment by filoozom** [comment]
Well, I guess that's why we have Travis 😛 
Strange, especially because it seems to work on NodeJS 7?

**Comment by prateekbh** [comment]
#272 fixes this as well
